# Generated by Django 3.1.7 on 2021-03-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmap', '0002_auto_20210320_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='ファイル1'),
        ),
    ]
