# Generated by Django 3.1.7 on 2021-03-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmap', '0003_auto_20210320_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='filename'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='original_name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Movie'),
        ),
    ]
