# Generated by Django 3.1.7 on 2021-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmap', '0004_auto_20210320_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='filename'),
        ),
    ]
