# Generated by Django 3.1.7 on 2021-03-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmap', '0005_auto_20210320_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
    ]
