apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    svc2pod: db
  ports:
  - port: 5432
    targetPort: db
  type: ClusterIP
  
  ---
apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels: 
    pod: db
spec:
  containers:
  - name: django_db
    image: postgres
    ports:
    - name: postgres
      containerPort: 5432
    # env:
    # - name: POSTGRES_PASSWORD
    #   value: postgres
    # - name: POSTGRES_DB
    #   value: postgres
    # - name: POSTGRES_USER
    #   value: postgres
