version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_web
    container_name: django_web
    restart: "no"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13.0
    container_name: django_db
    restart: "no"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_volume:/var/lib/postgresql/data

      
volumes:
  postgresql_volume:
    driver: local
