version: "3.7"

services:
  web:
    build:
      context: ./code/
      dockerfile: Dockerfile
    image: django_web
    container_name: django_web
    restart: "no"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: django_db
    restart: "no"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_volume:/var/lib/postgresql/data

      
volumes:
  postgresql_volume:
    driver: local
