version: "3.7"

services:
  db:
    image: postgres
    container_name: django_db
    restart: "no"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    build: .
    image: django_web
    container_name: django_web
    restart: "no"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

# volumes:
#   postgresql_volume:
#     driver: local
