apiVersion: v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
  minReadySeconds: 5
  selector:
    matchLabels:
      pod: web
  template:
    metadata:
      name: web
      labels: 
        pod: web
    spec:
      containers:
      - name: django_web
        image: hender14/django_web:20210408-155519
        ports:
        - name: http
          containerPort: 80
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    svc2pod: web
  ports:
  - port: 80
    targetPort: http
    nodePort: 30000
  type: NodePort
